name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement. Please describe what you'd like and why it would be useful.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? What's the current limitation?
      placeholder: "Currently there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: "A new MCP tool `foo.bar` that..."
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area does this affect?
      options:
        - MCP tools (new tool or tool enhancement)
        - Structured data / catalog
        - Design Lab (validate / render)
        - Token pipeline
        - Code generation
        - Composition (design.compose)
        - Mapping (map.*)
        - Accessibility
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any workarounds or alternative approaches?
    validations:
      required: false
