// @generated
// This file is auto-generated by @oods/schemas-tools.
// Do not edit manually; instead update the source JSON schemas and re-run the generator.

// Source: a11y.report.json
export namespace A11yReportSchema {
  /**
   * Structured WCAG accessibility scan report with per-rule contrast results.
   */
  export interface A11YReport {
    generatedAt: string;
    /**
     * Path to the token data used for evaluation.
     */
    tokenSource?: string;
    summary: {
      totalChecks: number;
      passed: number;
      failed: number;
      complianceStatus: 'compliant' | 'non-compliant';
    };
    rules: {
      ruleId: string;
      target: string;
      summary?: string;
      passed: boolean;
      ratio?: number;
      threshold: number;
      foreground?: {
        token?: string;
        hex?: string;
        cssVariable?: string;
      };
      background?: {
        token?: string;
        hex?: string;
        cssVariable?: string;
      };
      hint?: string;
    }[];
    /**
     * Component names from the scanned UiSchema, if provided.
     */
    components?: string[];
  }
}
export type A11yReport = A11yReportSchema.A11YReport;

// Source: a11y.scan.input.json
export namespace A11yScanInputSchema {
  /**
   * Accessibility scan input. Runs WCAG contrast checks against design tokens.
   */
  export interface A11YScanInput {
    /**
     * When true, write the a11y report artifact to the artifacts directory.
     */
    apply?: boolean;
    schema?: AgenticREPLUISchema;
  }
  /**
   * Optional UiSchema to include component inventory in the report.
   */
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
}
export type A11yScanInput = A11yScanInputSchema.A11YScanInput;

// Source: billing.reviewKit.input.json
export namespace BillingReviewKitInputSchema {
  /**
   * When true, writes review kit artifacts to the billing bundle directory.
   */
  export type ApplyChanges = boolean;
  /**
   * Billing object to include in the review kit bundle.
   */
  export type Object = 'Subscription' | 'Invoice' | 'Plan' | 'Usage';
  /**
   * Provider fixtures to compare in the review kit.
   *
   * @minItems 1
   */
  export type Fixtures = ['stripe' | 'chargebee', ...('stripe' | 'chargebee')[]];

  export interface BillingReviewKitInput {
    apply?: ApplyChanges;
    object: Object;
    fixtures?: Fixtures;
  }
}
export type BillingReviewKitInput = BillingReviewKitInputSchema.BillingReviewKitInput;

// Source: billing.switchFixtures.input.json
export namespace BillingSwitchFixturesInputSchema {
  /**
   * When true, records the fixture switch results as artifacts.
   */
  export type ApplyChanges = boolean;
  /**
   * Billing fixture provider to activate for Storybook scenarios.
   */
  export type Provider = 'stripe' | 'chargebee';

  export interface BillingSwitchFixturesInput {
    apply?: ApplyChanges;
    provider: Provider;
  }
}
export type BillingSwitchFixturesInput = BillingSwitchFixturesInputSchema.BillingSwitchFixturesInput;

// Source: brand.apply.input.json
export namespace BrandApplyInputSchema {
  export type BrandApplyInput = BrandApplyInput1 & BrandApplyInput2;
  export type BrandApplyInput1 = {
    [k: string]: any;
  };

  export interface BrandApplyInput2 {
    /**
     * Target brand identifier.
     */
    brand?: 'A';
    /**
     * Alias changes (object) or RFC 6902 patch array when strategy=patch.
     */
    delta:
      | {
          [k: string]: any;
        }
      | {
          op: 'add' | 'remove' | 'replace';
          path: string;
          value?: any;
        }[];
    /**
     * Alias strategy rewrites token values; patch applies RFC 6902 operations.
     */
    strategy?: 'alias' | 'patch';
    /**
     * Preview response controls (apply=false).
     */
    preview?: {
      /**
       * full includes structured before/after payloads; compact returns summary + hunks only.
       */
      verbosity?: 'full' | 'compact';
    };
    apply?: boolean;
  }
}
export type BrandApplyInput = BrandApplyInputSchema.BrandApplyInput;

// Source: brand.apply.output.json
export namespace BrandApplyOutputSchema {
  export interface BrandApplyOutput {
    artifacts: string[];
    diagnosticsPath?: string;
    transcriptPath: string;
    bundleIndexPath: string;
    preview?: {
      summary?: string;
      notes?: string[];
      diffs?: PlanDiff[];
      specimens?: string[];
    };
    artifactsDetail?: ArtifactDetail[];
  }
  export interface PlanDiff {
    path: string;
    status: 'added' | 'modified' | 'deleted';
    summary?: {
      additions?: number;
      deletions?: number;
    };
    hunks: PlanDiffHunk[];
    structured?: {
      type: string;
      before?: any;
      after?: any;
    };
  }
  export interface PlanDiffHunk {
    header: string;
    changes: PlanDiffChange[];
  }
  export interface PlanDiffChange {
    type: 'context' | 'add' | 'remove';
    value: string;
  }
  export interface ArtifactDetail {
    path: string;
    name: string;
    purpose?: string;
    sha256?: string;
    sizeBytes?: number;
  }
}
export type BrandApplyOutput = BrandApplyOutputSchema.BrandApplyOutput;

// Source: catalog.list.input.json
export namespace CatalogListInputSchema {
  export interface CatalogListInput {
    /**
     * Filter components by category (e.g., 'core', 'data')
     */
    category?: string;
    /**
     * Filter components by trait (e.g., 'Editable', 'Searchable')
     */
    trait?: string;
    /**
     * Filter components by context (e.g., 'detail', 'list')
     */
    context?: string;
    /**
     * Filter by component status. 'stable' = has renderer, 'planned' = not yet implemented.
     */
    status?: 'stable' | 'beta' | 'planned';
    /**
     * Response detail level. Defaults to summary for unfiltered calls, full when filters are provided.
     */
    detail?: 'summary' | 'full';
    /**
     * 1-based page index for pagination.
     */
    page?: number;
    /**
     * Number of components per page.
     */
    pageSize?: number;
  }
}
export type CatalogListInput = CatalogListInputSchema.CatalogListInput;

// Source: catalog.list.output.json
export namespace CatalogListOutputSchema {
  export interface CatalogListOutput {
    /**
     * Array of component catalog entries
     */
    components: {
      /**
       * Component name (e.g., 'Button', 'Card')
       */
      name: string;
      /**
       * Human-readable display name
       */
      displayName: string;
      /**
       * Component categories (e.g., ['core'], ['data'])
       */
      categories: string[];
      /**
       * Component tags for search and discovery
       */
      tags: string[];
      /**
       * Rendering contexts where component can be used
       */
      contexts: string[];
      /**
       * UI regions where component can appear
       */
      regions: string[];
      /**
       * List of trait capabilities (e.g., ['Editable', 'Searchable'])
       */
      traits: string[];
      /**
       * Component implementation status. 'stable' = has renderer, 'planned' = not yet implemented.
       */
      status: 'stable' | 'beta' | 'planned';
      /**
       * Maturity indicator derived from the source trait (e.g., 'stable', 'beta', 'draft').
       */
      maturity?: string;
      /**
       * DSL version since which this component is deprecated. When set, tools surface deprecation warnings in meta.warnings.
       */
      deprecated_since?: string;
      /**
       * Component prop schema with types and defaults (detail=full only).
       */
      propSchema?: {
        [k: string]: any;
      };
      /**
       * Slot definitions with accepted types and roles (detail=full only).
       */
      slots?: {
        [k: string]: {
          accept?: string[];
          role?: string;
          [k: string]: any;
        };
      };
      /**
       * References into Storybook `.stories.tsx` files (usage patterns + minimal snippets, detail=full only).
       */
      codeReferences?: {
        /**
         * Reference kind.
         */
        kind: 'storybook' | 'code-connect';
        /**
         * Repo-relative POSIX path to a source file containing a usage example.
         */
        path: string;
        /**
         * Storybook title when available.
         */
        title?: string;
        /**
         * Concise usage snippet extracted from the story file.
         */
        snippet: string;
      }[];
      /**
       * Convenience: best single snippet picked from codeReferences (detail=full only).
       */
      codeSnippet?: string;
    }[];
    /**
     * Total number of components that match the filters (before pagination).
     */
    totalCount: number;
    /**
     * Number of components returned in this page.
     */
    returnedCount: number;
    /**
     * 1-based page index used for pagination.
     */
    page: number;
    /**
     * Page size used for pagination. 0 when there are no results.
     */
    pageSize: number;
    /**
     * Whether more components are available after this page.
     */
    hasMore: boolean;
    /**
     * Detail level applied to component entries.
     */
    detail: 'summary' | 'full';
    /**
     * ISO timestamp when catalog was generated
     */
    generatedAt: string;
    stats: {
      /**
       * Total components in catalog
       */
      componentCount: number;
      /**
       * Total traits available
       */
      traitCount: number;
      /**
       * Total components matching the active filters
       */
      filteredCount?: number;
    };
    /**
     * All available category values that can be used for filtering. Sorted alphabetically.
     */
    availableCategories: string[];
    /**
     * Suggested filter values when a query returns zero results.
     */
    suggestions?: {
      /**
       * Closest matching trait names.
       */
      traits?: string[];
    };
  }
}
export type CatalogListOutput = CatalogListOutputSchema.CatalogListOutput;

// Source: code.generate.input.json
export namespace CodeGenerateInputSchema {
  /**
   * Generate framework-specific code from a validated UiSchema.
   */
  export type CodeGenerateInput = CodeGenerateInput1 & CodeGenerateInput2;
  export type CodeGenerateInput1 = {
    [k: string]: any;
  };

  export interface CodeGenerateInput2 {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0).
     */
    dslVersion?: string;
    schema?: AgenticREPLUISchema;
    /**
     * Reference to a cached UiSchema returned by design.compose.
     */
    schemaRef?: string;
    /**
     * Target framework for code generation. HTML delegates to existing repl.render document mode.
     */
    framework: 'react' | 'vue' | 'html';
    options?: {
      /**
       * When true, emit TypeScript prop types (React) or typed defineProps (Vue). Ignored for HTML.
       */
      typescript?: boolean;
      /**
       * Styling strategy: inline style objects, design-token CSS variables, or Tailwind utility classes.
       */
      styling?: 'inline' | 'tokens' | 'tailwind';
    };
  }
  /**
   * A validated UiSchema tree to generate code from.
   */
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
}
export type CodeGenerateInput = CodeGenerateInputSchema.CodeGenerateInput;

// Source: code.generate.output.json
export namespace CodeGenerateOutputSchema {
  /**
   * Generated framework-specific code from a UiSchema.
   */
  export interface CodeGenerateOutput {
    /**
     * Whether code generation succeeded.
     */
    status: 'ok' | 'error';
    /**
     * The target framework that was used.
     */
    framework: 'react' | 'vue' | 'html';
    /**
     * The generated source code. Empty string on error.
     */
    code: string;
    /**
     * Suggested file extension including the dot (e.g., '.tsx', '.vue', '.html').
     */
    fileExtension: string;
    /**
     * Import statements or package names required by the generated code.
     */
    imports: string[];
    /**
     * Non-fatal issues encountered during generation.
     */
    warnings: CodegenIssue[];
    /**
     * Fatal issues that prevented code generation.
     */
    errors?: CodegenIssue[];
    meta?: {
      nodeCount?: number;
      componentCount?: number;
      unknownComponents?: string[];
    };
  }
  export interface CodegenIssue {
    code: string;
    message: string;
    nodeId?: string;
    component?: string;
  }
}
export type CodeGenerateOutput = CodeGenerateOutputSchema.CodeGenerateOutput;

// Source: component-mapping.schema.json
export namespace ComponentMappingSchemaSchema {
  /**
   * Typed coercion transform. Discriminated union on the 'type' field.
   */
  export type CoercionDef =
    | {
        /**
         * Enum value mapping: source value lookup to target value.
         */
        type: 'enum';
        /**
         * Source value to target value mapping.
         */
        mapping: {
          [k: string]: string;
        };
      }
    | {
        /**
         * Convert boolean to string representation.
         */
        type: 'boolean_to_string';
        /**
         * String value when source is true.
         */
        trueValue: string;
        /**
         * String value when source is false.
         */
        falseValue: string;
      }
    | {
        /**
         * String interpolation using {{value}} placeholder.
         */
        type: 'template';
        /**
         * Template pattern with {{value}} placeholder.
         */
        pattern: string;
      }
    | {
        /**
         * Pass-through, no transformation.
         */
        type: 'identity';
      };

  /**
   * Schema for external design system component-to-OODS-trait mapping records. Enables onboarding external systems (Material, Ant, Chakra, etc.) into OODS.
   */
  export interface ComponentMappingSchema {
    $schema?: string;
    /**
     * ISO timestamp of last modification.
     */
    generatedAt: string;
    /**
     * Date-stamped version (e.g., '2026-02-28').
     */
    version: string;
    stats: {
      /**
       * Total number of component mappings.
       */
      mappingCount: number;
      /**
       * Number of distinct external systems.
       */
      systemCount: number;
    };
    /**
     * Array of component mapping records.
     */
    mappings: ComponentMapping[];
  }
  export interface ComponentMapping {
    /**
     * Unique mapping identifier (e.g., 'material-button').
     */
    id: string;
    /**
     * External design system name (e.g., 'material', 'ant-design', 'chakra').
     */
    externalSystem: string;
    /**
     * Component name in the external system (e.g., 'Button', 'TextField').
     */
    externalComponent: string;
    /**
     * OODS trait names this component maps to (e.g., ['Stateful', 'Taggable']).
     *
     * @minItems 1
     */
    oodsTraits: [string, ...string[]];
    /**
     * Property translations from external to OODS prop names.
     */
    propMappings?: PropMapping[];
    /**
     * 'auto' for machine-generated mappings, 'manual' for human-curated.
     */
    confidence: 'auto' | 'manual';
    metadata?: MappingMetadata;
  }
  export interface PropMapping {
    /**
     * Property name in the external system.
     */
    externalProp: string;
    /**
     * Corresponding OODS property name.
     */
    oodsProp: string;
    /**
     * Type coercion hint. null for direct pass-through.
     */
    coercion?: null | CoercionDef;
  }
  export interface MappingMetadata {
    /**
     * When the mapping was first created.
     */
    createdAt?: string;
    /**
     * When the mapping was last updated.
     */
    updatedAt?: string;
    /**
     * Who created or last edited this mapping.
     */
    author?: string;
    /**
     * Free-form notes about this mapping.
     */
    notes?: string;
  }
}
export type ComponentMappingSchema = ComponentMappingSchemaSchema.ComponentMappingSchema;

// Source: design.compose.input.json
export namespace DesignComposeInputSchema {
  /**
   * Generate a complete UiSchema from an intent description and/or object definition using layout templates and component selection. Provide at least one of 'intent' or 'object'.
   */
  export type DesignComposeInput = DesignComposeInput1 & DesignComposeInput2;
  export type DesignComposeInput1 = {
    [k: string]: any;
  };

  export interface DesignComposeInput2 {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0). Controls feature availability and deprecation behavior.
     */
    dslVersion?: string;
    /**
     * Natural-language description of the desired UI (e.g., 'dashboard with metrics and sidebar', 'user registration form').
     */
    intent?: string;
    /**
     * Object name from the OODS registry (e.g., 'Subscription', 'User'). When provided, composition uses trait-driven component placement via view_extensions.
     */
    object?: string;
    /**
     * View context for object-aware composition. Determines which view_extensions are applied. When object is provided without layout, context infers the layout (detail→detail, list→list, form→form).
     */
    context?: 'detail' | 'list' | 'form' | 'timeline' | 'card' | 'inline';
    /**
     * Layout template to use. 'auto' infers the best template from intent keywords.
     */
    layout?: 'dashboard' | 'form' | 'detail' | 'list' | 'card' | 'timeline' | 'auto';
    preferences?: {
      /**
       * Theme token (e.g., 'light', 'dark').
       */
      theme?: string;
      /**
       * Number of metric columns for dashboard layout.
       */
      metricColumns?: number;
      /**
       * Number of field groups for form layout.
       */
      fieldGroups?: number;
      /**
       * Number of tabs for detail layout.
       */
      tabCount?: number;
      /**
       * Custom tab labels for detail layout.
       */
      tabLabels?: string[];
      /**
       * Slot-name → component-name overrides (e.g., { 'items': 'Table' }).
       */
      componentOverrides?: {
        [k: string]: string;
      };
    };
    options?: {
      /**
       * Auto-validate the generated schema via repl.validate.
       */
      validate?: boolean;
      /**
       * Number of component candidates to return per slot.
       */
      topN?: number;
    };
  }
}
export type DesignComposeInput = DesignComposeInputSchema.DesignComposeInput;

// Source: design.compose.output.json
export namespace DesignComposeOutputSchema {
  /**
   * Generated UiSchema with component selections and validation result.
   */
  export interface DesignComposeOutput {
    /**
     * Whether composition succeeded.
     */
    status: 'ok' | 'error';
    /**
     * The layout template that was used.
     */
    layout: string;
    schema: AgenticREPLUISchema;
    /**
     * Server-managed reference to the generated schema for reuse in validate/render/code.generate.
     */
    schemaRef?: string;
    /**
     * ISO timestamp when the schemaRef was created.
     */
    schemaRefCreatedAt?: string;
    /**
     * ISO timestamp when the schemaRef expires.
     */
    schemaRefExpiresAt?: string;
    /**
     * Component selection results per slot.
     */
    selections: SlotSelection[];
    validation?: {
      status?: 'ok' | 'invalid' | 'skipped';
      errors?: Issue[];
      warnings?: Issue[];
    };
    /**
     * Non-fatal issues during composition.
     */
    warnings: Issue[];
    /**
     * Fatal issues that prevented composition.
     */
    errors?: Issue[];
    objectUsed?: {
      /**
       * Object name from the registry.
       */
      name: string;
      /**
       * Object version.
       */
      version: string;
      /**
       * Trait names composed into this object.
       */
      traits: string[];
      /**
       * Total fields from merged trait schemas.
       */
      fieldsComposed: number;
      /**
       * Count of view_extensions applied per context.
       */
      viewExtensionsApplied: {
        [k: string]: number;
      };
    };
    meta?: {
      intentParsed?: string;
      layoutDetected?: string;
      slotCount?: number;
      nodeCount?: number;
      /**
       * Object name auto-detected from intent string.
       */
      objectAutoDetected?: string;
      /**
       * Context auto-detected from intent string.
       */
      contextAutoDetected?: string;
      /**
       * True when intent was synthetically generated from object + context.
       */
      intentSynthetic?: boolean;
      /**
       * Human-readable warning messages from composition.
       */
      warnings?: string[];
      /**
       * Compositor intelligence indicators (Sprint 73).
       */
      intelligence?: {
        /**
         * Whether template slots were dynamically expanded.
         */
        fieldsExpanded?: boolean;
        /**
         * Number of slots added by expansion.
         */
        slotsExpanded?: number;
        /**
         * Reason for slot expansion.
         */
        expansionReason?: string;
        /**
         * Number of composite slot patterns applied.
         */
        patternsApplied?: number;
        /**
         * Detected multi-field pattern groups applied to slots (s83-m01).
         */
        patternGroups?: {
          slotName?: string;
          patternId?: string;
          compositeComponent?: string;
          matchedFields?: string[];
          confidence?: number;
        }[];
        /**
         * Whether position-aware scoring was used.
         */
        positionAffinityUsed?: boolean;
        /**
         * Whether field-type-aware scoring was used.
         */
        fieldAffinityUsed?: boolean;
        /**
         * Number of intent sections parsed from multi-section prompts.
         */
        intentSectionsParsed?: number;
        /**
         * Whether section context influenced slot composition.
         */
        sectionContextUsed?: boolean;
        /**
         * Aggregated composition confidence (0-1, average of per-slot raw confidences).
         */
        compositionConfidence?: number;
        /**
         * Count of slots with confidence below 0.5 that have alternative candidates.
         */
        lowConfidenceSlots?: number;
        /**
         * Slot names whose selected component scored below the low-confidence threshold.
         */
        lowConfidenceSlotNames?: string[];
      };
    };
  }
  /**
   * The generated UiSchema (with slot placeholders intact for agent customization).
   */
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
  export interface SlotSelection {
    slotName: string;
    intent: string;
    selectedComponent?: string;
    /**
     * Raw confidence score (0-1) before normalization.
     */
    confidence?: number;
    /**
     * Human-readable confidence band for quick review.
     */
    confidenceLevel: 'high' | 'medium' | 'low';
    /**
     * One-line rationale describing why this component was selected.
     */
    explanation: string;
    /**
     * Follow-up guidance when a low-confidence slot should be reviewed or overridden.
     */
    reviewHint?: string;
    candidates: {
      name: string;
      confidence: number;
      reason: string;
      keywordTagMatches?: number;
      keywordTraitMatches?: number;
      contextTagMatches?: number;
      contextTraitMatches?: number;
    }[];
    /**
     * Alternative candidates surfaced when confidence < 0.5.
     */
    alternativeCandidates?: {
      name: string;
      confidence: number;
      reason: string;
      keywordTagMatches?: number;
      keywordTraitMatches?: number;
      contextTagMatches?: number;
      contextTraitMatches?: number;
    }[];
  }
  export interface Issue {
    code: string;
    message: string;
    path?: string;
    hint?: string;
  }
}
export type DesignComposeOutput = DesignComposeOutputSchema.DesignComposeOutput;

// Source: generic.input.json
export namespace GenericInputSchema {
  export interface GenericInput {
    apply?: boolean;
  }
}
export type GenericInput = GenericInputSchema.GenericInput;

// Source: generic.output.json
export namespace GenericOutputSchema {
  export interface GenericOutput {
    status?: 'ok' | 'error' | 'invalid';
    notes?: string;
    logs?: string[];
    artifacts: (
      | string
      | {
          path: string;
          name?: string;
          purpose?: string;
          sha256?: string;
          sizeBytes?: number;
        }
    )[];
    diagnosticsPath?: string;
    transcriptPath: string;
    bundleIndexPath: string;
    structuredData?: {
      [k: string]: any;
    };
    artifactsDetail?: {
      path: string;
      name?: string;
      purpose?: string;
      sha256?: string;
      sizeBytes?: number;
      [k: string]: any;
    }[];
    preview?: {
      summary?: string;
      notes?: string[];
      diffs?: {
        path: string;
        status: 'added' | 'modified' | 'deleted';
        summary?: {
          additions?: number;
          deletions?: number;
        };
        hunks: {
          header: string;
          changes: {
            type: 'context' | 'add' | 'remove';
            value: any;
          }[];
        }[];
        structured?: {
          type: 'json';
          before?: any;
          after?: any;
        };
      }[];
      specimens?: string[];
    };
  }
}
export type GenericOutput = GenericOutputSchema.GenericOutput;

// Source: health.input.json
export namespace HealthInputSchema {
  export interface HealthInput {
    /**
     * When true, include DSL version changelog in the response.
     */
    includeChangelog?: boolean;
    /**
     * When provided with includeChangelog, only return changelog entries since this version.
     */
    sinceVersion?: string;
  }
}
export type HealthInput = HealthInputSchema.HealthInput;

// Source: health.output.json
export namespace HealthOutputSchema {
  export interface HealthOutput {
    status: 'ok' | 'degraded';
    server: {
      version: string;
      uptime: number;
    };
    registry: {
      components: number;
      traits: number;
      objects: number;
      lastSync: string;
    };
    tokens: {
      built: boolean;
      theme: string;
      brand: string;
    };
    schemas: {
      savedCount: number;
      storeDir: string;
    };
    latency: number;
    warnings?: string[];
    /**
     * Current DSL version of this server.
     */
    dslVersion?: string;
    /**
     * DSL version changelog entries, included when requested via includeChangelog input.
     */
    changelog?: {
      version: string;
      date: string;
      changes: string[];
      breaking: boolean;
    }[];
  }
}
export type HealthOutput = HealthOutputSchema.HealthOutput;

// Source: json-schema-draft-07.json
export namespace JsonSchemaDraft07Schema {
  export type JsonSchemaDraft07 = JsonSchemaDraft071 & JsonSchemaDraft072;
  export type NonNegativeInteger = number;
  export type NonNegativeIntegerDefault0 = NonNegativeInteger;
  export type JsonSchemaDraft072 =
    | {
        $id?: string;
        $schema?: string;
        $ref?: string;
        $comment?: string;
        title?: string;
        description?: string;
        default?: any;
        readOnly?: boolean;
        examples?: any[];
        multipleOf?: number;
        maximum?: number;
        exclusiveMaximum?: number;
        minimum?: number;
        exclusiveMinimum?: number;
        maxLength?: NonNegativeInteger;
        minLength?: NonNegativeIntegerDefault0;
        pattern?: string;
        additionalItems?: JsonSchemaDraft072;
        items?: JsonSchemaDraft072 | SchemaArray;
        maxItems?: NonNegativeInteger;
        minItems?: NonNegativeIntegerDefault0;
        uniqueItems?: boolean;
        contains?: JsonSchemaDraft072;
        maxProperties?: NonNegativeInteger;
        minProperties?: NonNegativeIntegerDefault0;
        required?: StringArray;
        additionalProperties?: JsonSchemaDraft072;
        definitions?: {
          [k: string]: JsonSchemaDraft072;
        };
        properties?: {
          [k: string]: JsonSchemaDraft072;
        };
        patternProperties?: {
          [k: string]: JsonSchemaDraft072;
        };
        dependencies?: {
          [k: string]: JsonSchemaDraft072 | StringArray;
        };
        propertyNames?: JsonSchemaDraft072;
        const?: any;
        /**
         * @minItems 1
         */
        enum?: [any, ...any[]];
        type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
        format?: string;
        contentMediaType?: string;
        contentEncoding?: string;
        if?: JsonSchemaDraft072;
        then?: JsonSchemaDraft072;
        else?: JsonSchemaDraft072;
        allOf?: SchemaArray;
        anyOf?: SchemaArray;
        oneOf?: SchemaArray;
        not?: JsonSchemaDraft072;
        [k: string]: any;
      }
    | boolean;
  /**
   * @minItems 1
   */
  export type SchemaArray = [JsonSchemaDraft072, ...JsonSchemaDraft072[]];
  export type StringArray = string[];
  export type SimpleTypes = 'array' | 'boolean' | 'integer' | 'null' | 'number' | 'object' | 'string';

  export interface JsonSchemaDraft071 {
    $id?: string;
    $schema?: string;
    $ref?: string;
    $comment?: string;
    title?: string;
    description?: string;
    default?: any;
    readOnly?: boolean;
    examples?: any[];
    multipleOf?: number;
    maximum?: number;
    exclusiveMaximum?: number;
    minimum?: number;
    exclusiveMinimum?: number;
    maxLength?: NonNegativeInteger;
    minLength?: NonNegativeIntegerDefault0;
    pattern?: string;
    additionalItems?: JsonSchemaDraft072;
    items?: JsonSchemaDraft072 | SchemaArray;
    maxItems?: NonNegativeInteger;
    minItems?: NonNegativeIntegerDefault0;
    uniqueItems?: boolean;
    contains?: JsonSchemaDraft072;
    maxProperties?: NonNegativeInteger;
    minProperties?: NonNegativeIntegerDefault0;
    required?: StringArray;
    additionalProperties?: JsonSchemaDraft072;
    definitions?: {
      [k: string]: JsonSchemaDraft072;
    };
    properties?: {
      [k: string]: JsonSchemaDraft072;
    };
    patternProperties?: {
      [k: string]: JsonSchemaDraft072;
    };
    dependencies?: {
      [k: string]: JsonSchemaDraft072 | StringArray;
    };
    propertyNames?: JsonSchemaDraft072;
    const?: any;
    /**
     * @minItems 1
     */
    enum?: [any, ...any[]];
    type?: SimpleTypes | [SimpleTypes, ...SimpleTypes[]];
    format?: string;
    contentMediaType?: string;
    contentEncoding?: string;
    if?: JsonSchemaDraft072;
    then?: JsonSchemaDraft072;
    else?: JsonSchemaDraft072;
    allOf?: SchemaArray;
    anyOf?: SchemaArray;
    oneOf?: SchemaArray;
    not?: JsonSchemaDraft072;
    [k: string]: any;
  }
}
export type JsonSchemaDraft07 = JsonSchemaDraft07Schema.JsonSchemaDraft07;

// Source: map.apply.input.json
export namespace MapApplyInputSchema {
  /**
   * Apply Stage1 reconciliation verdicts to the component-mapping registry. Accepts exactly one of inline report or reportPath.
   */
  export type MapApplyInput = MapApplyInput1 & MapApplyInput2;
  export type CandidateObject = CandidateObject1 & {
    object_id: string;
    name: string;
    role: string;
    inferred_role?: string;
    inferred_role_score?: number;
    confidence: number;
    /**
     * @minItems 1
     */
    recommended_oods_traits: [string, ...string[]];
    recommended_domain?: string;
    action: 'create' | 'patch' | 'skip' | 'conflict';
    reasoning: string;
    verdict_reasoning?: string;
    existing_map_id?: string;
    diff?: CandidateDiff;
    alternate_interpretations?: AlternateInterpretation[];
    evidence_chain?: EvidenceRef[];
  };
  export type CandidateObject1 = {
    [k: string]: any;
  } & {
    [k: string]: any;
  } & {
    [k: string]: any;
  };
  export type AlternateInterpretation =
    | string
    | {
        role: string;
        score: number;
        reasoning: string;
      };
  export type AlternateVerb =
    | string
    | {
        verb_id: string;
        score: number;
        reasoning: string;
      };
  export type MapApplyInput2 = {
    [k: string]: any;
  };

  export interface MapApplyInput1 {
    /**
     * When true, persist registry mutations. Defaults to dry-run.
     */
    apply?: boolean;
    /**
     * Candidates below this threshold are routed to queued instead of being applied.
     */
    minConfidence?: number;
    /**
     * Filesystem path to a reconciliation_report.json artifact.
     */
    reportPath?: string;
    report?: ReconciliationReport;
  }
  export interface ReconciliationReport {
    kind: 'reconciliation_report';
    schema_version: string;
    generated_at: string;
    target: {
      id: string;
      url?: string;
    };
    /**
     * @minItems 1
     */
    candidate_objects: [CandidateObject, ...CandidateObject1[]];
    candidate_actions?: CandidateAction[];
    candidate_traits?: {
      [k: string]: any;
    }[];
    conflicts?: Conflict[];
    coverage_gaps?: {
      [k: string]: any;
    }[];
    validation_failures?: {
      [k: string]: any;
    }[];
    manifest?: Manifest;
    reconciliation_summary?: ReconciliationSummary;
  }
  export interface CandidateDiff {
    added_traits: string[];
    removed_traits: string[];
    changed_fields: CandidateDiffField[];
  }
  export interface CandidateDiffField {
    field: string;
    from?: any;
    to?: any;
  }
  export interface EvidenceRef {
    [k: string]: any;
  }
  export interface CandidateAction {
    action_id: string;
    name: string;
    verb: string;
    source_object_id?: string;
    confidence?: number;
    suggested_oods_trait?: string;
    suggested_action?: string;
    reasoning?: string;
    alternate_verbs?: AlternateVerb[];
    preconditions?: ActionPrecondition[];
  }
  export interface ActionPrecondition {
    type: 'auth' | 'role' | 'state' | 'data';
    description?: string;
    confidence?: number;
    evidence_chain?: EvidenceRef[];
  }
  export interface Conflict {
    type: string;
    description: string;
    severity: 'info' | 'warning' | 'error';
    action_id?: string;
    object_id?: string;
    existing_map_id?: string;
  }
  export interface Manifest {
    inputs?: {
      oods_registry_fetch?: RegistryFetchTelemetry;
    };
  }
  export interface RegistryFetchTelemetry {
    source: 'pre-supplied' | 'transport' | 'empty-fallback';
    entries_count: number;
    warnings?: string[];
  }
  export interface ReconciliationSummary {
    mode: string;
    existing_map_count: number;
    verdict_counts: {
      create?: number;
      patch?: number;
      skip?: number;
      conflict?: number;
    };
  }
}
export type MapApplyInput = MapApplyInputSchema.MapApplyInput;

// Source: map.apply.output.json
export namespace MapApplyOutputSchema {
  /**
   * Dry-run or apply report for Stage1 reconciliation verdict routing.
   */
  export interface MapApplyOutput {
    applied: AppliedRoute[];
    skipped: SkippedRoute[];
    queued: QueuedRoute[];
    conflicted: ConflictRoute[];
    errors: ApplyError[];
    diff: DiffSummary;
    conflictArtifactPath?: string;
    etag: string;
  }
  export interface AppliedRoute {
    objectId: string;
    name: string;
    action: 'create' | 'patch';
    confidence: number;
    /**
     * @minItems 1
     */
    recommendedOodsTraits: [string, ...string[]];
    existingMapId?: string;
    mappingId?: string;
    reason: string;
    persisted: boolean;
    diff?: CandidateDiff;
  }
  export interface CandidateDiff {
    added_traits: string[];
    removed_traits: string[];
    changed_fields: CandidateDiffField[];
  }
  export interface CandidateDiffField {
    field: string;
    from?: any;
    to?: any;
  }
  export interface SkippedRoute {
    objectId: string;
    name: string;
    action: 'skip';
    confidence: number;
    /**
     * @minItems 1
     */
    recommendedOodsTraits: [string, ...string[]];
    existingMapId?: string;
    mappingId?: string;
    reason: string;
    persisted: boolean;
    diff?: CandidateDiff;
  }
  export interface QueuedRoute {
    objectId: string;
    name: string;
    action: 'create' | 'patch' | 'skip' | 'conflict';
    confidence: number;
    threshold: number;
    queueReason: 'below_confidence';
    /**
     * @minItems 1
     */
    recommendedOodsTraits: [string, ...string[]];
    existingMapId?: string;
    reason: string;
    diff?: CandidateDiff;
  }
  export interface ConflictRoute {
    objectId: string;
    name: string;
    action: 'conflict';
    confidence: number;
    existingMapId?: string;
    reason: string;
  }
  export interface ApplyError {
    objectId?: string;
    name?: string;
    action?: 'create' | 'patch' | 'skip' | 'conflict';
    message: string;
    details?: {
      [k: string]: any;
    };
  }
  export interface DiffSummary {
    create: number;
    patch: number;
    skip: number;
    conflict: number;
    queued: number;
    changedFields: string[];
    addedTraits: string[];
    removedTraits: string[];
  }
}
export type MapApplyOutput = MapApplyOutputSchema.MapApplyOutput;

// Source: map.create.input.json
export namespace MapCreateInputSchema {
  /**
   * Create a component-to-trait mapping for an external design system component.
   */
  export interface MapCreateInput {
    /**
     * When true, write changes to disk.
     */
    apply?: boolean;
    /**
     * External design system name (e.g., 'material', 'ant-design', 'chakra').
     */
    externalSystem: string;
    /**
     * Component name in the external system (e.g., 'Button', 'TextField').
     */
    externalComponent: string;
    /**
     * OODS trait names this component maps to.
     *
     * @minItems 1
     */
    oodsTraits: [string, ...string[]];
    /**
     * Property translations from external to OODS prop names.
     */
    propMappings?: {
      externalProp: string;
      oodsProp: string;
      coercion?:
        | null
        | {
            type: 'enum';
            mapping: {
              [k: string]: string;
            };
          }
        | {
            type: 'boolean_to_string';
            trueValue: string;
            falseValue: string;
          }
        | {
            type: 'template';
            pattern: string;
          }
        | {
            type: 'identity';
          };
    }[];
    /**
     * 'auto' for machine-generated, 'manual' for human-curated.
     */
    confidence?: 'auto' | 'manual';
    metadata?: {
      author?: string;
      notes?: string;
    };
  }
}
export type MapCreateInput = MapCreateInputSchema.MapCreateInput;

// Source: map.create.output.json
export namespace MapCreateOutputSchema {
  /**
   * Result of creating a component-to-trait mapping.
   */
  export interface MapCreateOutput {
    status: 'ok' | 'error';
    /**
     * The created mapping record.
     */
    mapping: {
      [k: string]: any;
    };
    /**
     * SHA256 ETag of the updated mappings file.
     */
    etag: string;
    /**
     * Whether the mapping was persisted to disk.
     */
    applied?: boolean;
    /**
     * Non-fatal warnings (e.g., unknown traits).
     */
    warnings?: string[];
    /**
     * Agent-friendly error details following formatValidationErrors().
     */
    errors?: {
      message: string;
      details: {
        field: string;
        message: string;
        keyword: string;
      }[];
    };
  }
}
export type MapCreateOutput = MapCreateOutputSchema.MapCreateOutput;

// Source: map.delete.input.json
export namespace MapDeleteInputSchema {
  /**
   * Delete a component-to-trait mapping by ID.
   */
  export interface MapDeleteInput {
    /**
     * Mapping ID to delete (e.g., 'material-button').
     */
    id: string;
  }
}
export type MapDeleteInput = MapDeleteInputSchema.MapDeleteInput;

// Source: map.delete.output.json
export namespace MapDeleteOutputSchema {
  /**
   * Result of deleting a component-to-trait mapping.
   */
  export interface MapDeleteOutput {
    status: 'ok' | 'error';
    /**
     * Summary of the deleted mapping.
     */
    deleted?: {
      id?: string;
      externalSystem?: string;
      externalComponent?: string;
      [k: string]: any;
    };
    /**
     * SHA256 etag of the mappings file after deletion.
     */
    etag?: string;
    /**
     * Error message when status=error.
     */
    message?: string;
  }
}
export type MapDeleteOutput = MapDeleteOutputSchema.MapDeleteOutput;

// Source: map.list.input.json
export namespace MapListInputSchema {
  /**
   * List component-to-trait mappings, optionally filtered by external system.
   */
  export interface MapListInput {
    /**
     * Filter mappings to a specific external system (e.g., 'material').
     */
    externalSystem?: string;
    /**
     * Pagination cursor. Use the previous page's nextCursor to continue. When cursor or limit is provided, pagination defaults to 100 items per page.
     */
    cursor?: string;
    /**
     * Page size for pagination. Omitting both cursor and limit preserves the legacy full-list response.
     */
    limit?: number;
  }
}
export type MapListInput = MapListInputSchema.MapListInput;

// Source: map.list.output.json
export namespace MapListOutputSchema {
  /**
   * List of component-to-trait mappings.
   */
  export interface MapListOutput {
    /**
     * Matching mapping records.
     */
    mappings: {
      [k: string]: any;
    }[];
    /**
     * Number of mappings returned.
     */
    totalCount: number;
    stats: {
      mappingCount: number;
      systemCount: number;
    };
    /**
     * Current ETag of the mappings file.
     */
    etag: string;
    /**
     * Pagination cursor for the next page when additional mappings remain.
     */
    nextCursor?: string;
  }
}
export type MapListOutput = MapListOutputSchema.MapListOutput;

// Source: map.resolve.input.json
export namespace MapResolveInputSchema {
  /**
   * Resolve an external component to its OODS trait mapping with prop translations.
   */
  export interface MapResolveInput {
    /**
     * External design system name (e.g., 'material').
     */
    externalSystem: string;
    /**
     * Component name in the external system (e.g., 'Button').
     */
    externalComponent: string;
  }
}
export type MapResolveInput = MapResolveInputSchema.MapResolveInput;

// Source: map.resolve.output.json
export namespace MapResolveOutputSchema {
  /**
   * Resolved OODS trait mapping for an external component.
   */
  export interface MapResolveOutput {
    status: 'ok' | 'not_found';
    /**
     * The resolved mapping record (present when status=ok).
     */
    mapping?: {
      [k: string]: any;
    };
    /**
     * Flattened prop translations with coercion details.
     */
    propTranslations?: {
      externalProp: string;
      oodsProp: string;
      coercionType?: string | null;
      coercionDetail?: {
        [k: string]: any;
      } | null;
      [k: string]: any;
    }[];
    /**
     * Explanation when status=not_found.
     */
    message?: string;
  }
}
export type MapResolveOutput = MapResolveOutputSchema.MapResolveOutput;

// Source: map.update.input.json
export namespace MapUpdateInputSchema {
  /**
   * Partially update an existing component-to-trait mapping.
   */
  export interface MapUpdateInput {
    /**
     * Mapping ID to update (e.g., 'material-button').
     */
    id: string;
    /**
     * Fields to update. Only provided fields are changed.
     */
    updates: {
      /**
       * Replace OODS trait list.
       *
       * @minItems 1
       */
      oodsTraits?: [string, ...string[]];
      /**
       * Update confidence level.
       */
      confidence?: 'auto' | 'manual';
      /**
       * Replace property mappings.
       */
      propMappings?: {
        externalProp: string;
        oodsProp: string;
        coercion?:
          | null
          | {
              type: 'enum';
              mapping: {
                [k: string]: string;
              };
            }
          | {
              type: 'boolean_to_string';
              trueValue: string;
              falseValue: string;
            }
          | {
              type: 'template';
              pattern: string;
            }
          | {
              type: 'identity';
            };
      }[];
      /**
       * Update notes in metadata.
       */
      notes?: string;
    };
  }
}
export type MapUpdateInput = MapUpdateInputSchema.MapUpdateInput;

// Source: map.update.output.json
export namespace MapUpdateOutputSchema {
  /**
   * Result of updating a component-to-trait mapping.
   */
  export interface MapUpdateOutput {
    status: 'ok' | 'error';
    /**
     * The updated mapping record (present when status=ok).
     */
    mapping?: {
      [k: string]: any;
    };
    /**
     * SHA256 etag of the mappings file after update.
     */
    etag?: string;
    /**
     * List of fields that were changed.
     */
    changes?: string[];
    /**
     * Error or informational message.
     */
    message?: string;
  }
}
export type MapUpdateOutput = MapUpdateOutputSchema.MapUpdateOutput;

// Source: object.list.input.json
export namespace ObjectListInputSchema {
  export interface ObjectListInput {
    /**
     * Filter to objects in a specific domain (e.g. 'core.identity', 'saas.billing')
     */
    domain?: string;
    /**
     * Filter by metadata maturity level
     */
    maturity?: 'draft' | 'alpha' | 'beta' | 'stable';
    /**
     * Filter to objects composing a given trait (e.g. 'Priceable', 'lifecycle/Stateful')
     */
    trait?: string;
  }
}
export type ObjectListInput = ObjectListInputSchema.ObjectListInput;

// Source: object.list.output.json
export namespace ObjectListOutputSchema {
  export interface ObjectListOutput {
    objects: {
      name: string;
      domain: string;
      version: string;
      maturity: string | null;
      description: string;
      traits: string[];
      fieldCount: number;
      tags: string[];
    }[];
    totalCount: number;
    filters: {
      domain: string | null;
      maturity: string | null;
      trait: string | null;
    };
  }
}
export type ObjectListOutput = ObjectListOutputSchema.ObjectListOutput;

// Source: object.show.input.json
export namespace ObjectShowInputSchema {
  export interface ObjectShowInput {
    /**
     * Object name to look up (e.g. 'User', 'Product', 'Invoice')
     */
    name: string;
    /**
     * Optional: filter view_extensions to a single context (e.g. 'detail', 'list', 'form', 'timeline', 'card', 'inline')
     */
    context?: string;
  }
}
export type ObjectShowInput = ObjectShowInputSchema.ObjectShowInput;

// Source: object.show.output.json
export namespace ObjectShowOutputSchema {
  export interface ObjectShowOutput {
    name: string;
    version: string;
    domain: string;
    description: string;
    tags: string[];
    maturity: string | null;
    traits: {
      name: string;
      alias: string | null;
      parameters: {
        [k: string]: any;
      } | null;
    }[];
    schema: {
      [k: string]: {
        type: string;
        required: boolean;
        description: string;
        default?: any;
        defaultFromParameter?: string;
        validation?: {
          [k: string]: any;
        };
        [k: string]: any;
      };
    };
    semantics: {
      [k: string]: {
        semantic_type: string;
        token_mapping: string;
        ui_hints?: {
          [k: string]: string | boolean | number;
        };
      };
    };
    viewExtensions: {
      [k: string]: {
        component: string;
        position?: string;
        priority?: number;
        props?: {
          [k: string]: any;
        };
      }[];
    };
    tokens: {
      [k: string]: any;
    };
    warnings: string[];
    filePath: string;
  }
}
export type ObjectShowOutput = ObjectShowOutputSchema.ObjectShowOutput;

// Source: pipeline.input.json
export namespace PipelineInputSchema {
  /**
   * Execute the full design pipeline (compose -> validate -> render -> codegen) in a single call.
   */
  export interface PipelineInput {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0).
     */
    dslVersion?: string;
    /**
     * Object name from the OODS registry (e.g., Subscription, User).
     */
    object?: string;
    /**
     * Natural-language description of the desired UI.
     */
    intent?: string;
    /**
     * View context for object-aware composition.
     */
    context?: 'detail' | 'list' | 'form' | 'timeline' | 'card' | 'inline';
    /**
     * Layout template to use.
     */
    layout?: 'dashboard' | 'form' | 'detail' | 'list' | 'card' | 'timeline' | 'auto';
    preferences?: {
      /**
       * Theme token (e.g., 'light', 'dark').
       */
      theme?: string;
      /**
       * Number of metric columns for dashboard layout.
       */
      metricColumns?: number;
      /**
       * Number of field groups for form layout.
       */
      fieldGroups?: number;
      /**
       * Number of tabs for detail layout.
       */
      tabCount?: number;
      /**
       * Custom tab labels for detail layout.
       */
      tabLabels?: string[];
      /**
       * Slot-name to component-name overrides (e.g., { 'items': 'Table' }).
       */
      componentOverrides?: {
        [k: string]: string;
      };
    };
    /**
     * Sprint 88: Stage1 BridgeSummary action_mappings, flat verb-keyed entries. See docs/integration/stage1-oods-contract.md §2c.
     */
    actionMappings?: {
      verb: string;
      oodsTrait?: string;
      trait?: string;
      object?: string;
      component?: string;
      slot?: string;
      confidence?: number;
      [k: string]: any;
    }[];
    /**
     * Target framework for code generation.
     */
    framework?: 'react' | 'vue' | 'html';
    /**
     * Styling strategy for code generation.
     */
    styling?: 'inline' | 'tokens' | 'tailwind';
    /**
     * Optional schema save config. String for name-only, or { name, tags } for full control.
     */
    save?:
      | string
      | {
          /**
           * Schema name to persist.
           */
          name: string;
          /**
           * Tags to attach to the saved schema.
           */
          tags?: string[];
        };
    options?: {
      /**
       * Skip the validate step (default false).
       */
      skipValidation?: boolean;
      /**
       * Skip the render step (default false).
       */
      skipRender?: boolean;
      /**
       * Enable a11y contrast checks in validate (default false).
       */
      checkA11y?: boolean;
      /**
       * Render with apply=true to include HTML output (default true).
       */
      renderApply?: boolean;
      /**
       * When true (default), omit token CSS from render output and return tokenCssRef instead. Reduces response size by ~40%.
       */
      compact?: boolean;
      /**
       * Alias: enable TypeScript output in code generation.
       */
      typescript?: boolean;
      /**
       * Alias: styling strategy. Overridden by top-level styling if both provided.
       */
      styling?: 'inline' | 'tokens' | 'tailwind';
      /**
       * Alias: target framework. Overridden by top-level framework if both provided.
       */
      framework?: 'react' | 'vue' | 'html';
    };
  }
}
export type PipelineInput = PipelineInputSchema.PipelineInput;

// Source: pipeline.output.json
export namespace PipelineOutputSchema {
  /**
   * Aggregated pipeline response with partial results and explicit failure step metadata.
   */
  export interface PipelineOutput {
    /**
     * Schema reference returned by compose, reusable across tools.
     */
    schemaRef?: string;
    /**
     * ISO timestamp when the schemaRef was created.
     */
    schemaRefCreatedAt?: string;
    /**
     * ISO timestamp when the schemaRef expires. Use schema.save to persist before expiry.
     */
    schemaRefExpiresAt?: string;
    /**
     * Proactive warning when schemaRef TTL is approaching expiration (< 5 minutes remaining).
     */
    schemaRefTtlWarning?: {
      /**
       * Human-readable warning message.
       */
      message: string;
      /**
       * Milliseconds remaining until schemaRef expires.
       */
      remainingMs: number;
      /**
       * Actionable recommendation for the agent.
       */
      recommendation: string;
    };
    compose: {
      object?: string;
      context?: string;
      layout: string;
      componentCount: number;
      /**
       * Sprint 88: verbs grouped by trait after action_mappings reconciliation.
       */
      resolvedActions?: {
        trait: string;
        verbs: string[];
      }[];
    };
    validation?: {
      status: 'ok' | 'invalid' | 'skipped';
      errors: Issue[];
      warnings: Issue[];
    };
    render?: {
      /**
       * Rendered HTML when renderApply=true.
       */
      html?: string;
      /**
       * Reference to token CSS artifact when compact mode is enabled.
       */
      tokenCssRef?: string;
      /**
       * Render metadata summary.
       */
      meta: {
        [k: string]: any;
      };
    };
    code?: {
      framework: 'react' | 'vue' | 'html';
      styling: 'inline' | 'tokens' | 'tailwind';
      output: string;
    };
    saved?: {
      name: string;
      version: number;
    };
    /**
     * One-line natural language description of what was generated.
     */
    summary?: string;
    /**
     * Quality metrics for the pipeline output.
     */
    metrics?: {
      totalNodes?: number;
      componentsUsed?: number;
      fieldsBound?: number;
      responseBytes?: number;
      fieldsOmitted?: {
        field: string;
        reason: string;
      }[];
    };
    pipeline: {
      steps: ('compose' | 'validate' | 'render' | 'codegen' | 'save')[];
      /**
       * Per-step latency in milliseconds.
       */
      stepLatency?: {
        [k: string]: number;
      };
      duration: number;
    };
    error?: {
      step: 'compose' | 'validate' | 'render' | 'codegen' | 'save';
      code: string;
      message: string;
    };
  }
  export interface Issue {
    code: string;
    message: string;
    path?: string;
    hint?: string;
    severity?: string;
    nodeId?: string;
    component?: string;
  }
}
export type PipelineOutput = PipelineOutputSchema.PipelineOutput;

// Source: registry.snapshot.input.json
export namespace RegistrySnapshotInputSchema {
  /**
   * Bulk-read the current OODS registry state (maps, traits, objects) in a single call.
   */
  export interface RegistrySnapshotInput {}
}
export type RegistrySnapshotInput = RegistrySnapshotInputSchema.RegistrySnapshotInput;

// Source: registry.snapshot.output.json
export namespace RegistrySnapshotOutputSchema {
  /**
   * Single-call bulk snapshot of the mapping registry plus trait/object catalogs.
   */
  export interface RegistrySnapshotOutput {
    maps: {
      [k: string]: any;
    }[];
    traits: {
      [k: string]: TraitInfo;
    };
    objects: {
      [k: string]: ObjectInfo;
    };
    etag: string;
    generatedAt: string;
  }
  export interface TraitInfo {
    name: string;
    version: string;
    description: string;
    category: string;
    tags?: string[];
    contexts?: string[];
    viewExtensions?: {
      [k: string]: any;
    }[];
    parameters?: {
      [k: string]: any;
    }[];
    schema?: {
      [k: string]: any;
    };
    semantics?: {
      [k: string]: any;
    };
    tokens?: {
      [k: string]: any;
    };
    dependencies?: string[];
    metadata?: {
      [k: string]: any;
    };
    objects?: string[];
    source?: string;
  }
  export interface ObjectInfo {
    name: string;
    version: string;
    domain: string;
    description: string;
    tags?: string[];
    traits?: TraitRef[];
    fields?: string[];
    semantics?: {
      [k: string]: any;
    };
    tokens?: {
      [k: string]: any;
    };
    metadata?: {
      [k: string]: any;
    };
    source?: string;
  }
  export interface TraitRef {
    reference: string;
    alias?: string | null;
    parameters?: {
      [k: string]: any;
    };
  }
}
export type RegistrySnapshotOutput = RegistrySnapshotOutputSchema.RegistrySnapshotOutput;

// Source: release.tag.input.json
export namespace ReleaseTagInputSchema {
  export interface ReleaseTagInput {
    apply?: boolean;
    tag: string;
    message?: string | null;
  }
}
export type ReleaseTagInput = ReleaseTagInputSchema.ReleaseTagInput;

// Source: release.tag.output.json
export namespace ReleaseTagOutputSchema {
  export interface ReleaseTagOutput {
    artifacts: string[];
    transcriptPath: string;
    bundleIndexPath: string;
    tag: string;
    created: boolean;
    warnings?: string[];
  }
}
export type ReleaseTagOutput = ReleaseTagOutputSchema.ReleaseTagOutput;

// Source: release.verify.input.json
export namespace ReleaseVerifyInputSchema {
  export interface ReleaseVerifyInput {
    apply?: boolean;
    /**
     * @minItems 1
     */
    packages?: [
      '@oods/tokens' | '@oods/tw-variants' | '@oods/a11y-tools',
      ...('@oods/tokens' | '@oods/tw-variants' | '@oods/a11y-tools')[]
    ];
    fromTag?: string;
  }
}
export type ReleaseVerifyInput = ReleaseVerifyInputSchema.ReleaseVerifyInput;

// Source: release.verify.output.json
export namespace ReleaseVerifyOutputSchema {
  export interface ReleaseVerifyOutput {
    artifacts: string[];
    diagnosticsPath?: string;
    transcriptPath: string;
    bundleIndexPath: string;
    results: {
      name: string;
      version: string;
      identical: boolean;
      sha256: string;
      sizeBytes: number;
      warnings?: string[];
      files?: string[];
    }[];
    changelogPath: string;
    summary: string;
    warnings?: string[];
  }
}
export type ReleaseVerifyOutput = ReleaseVerifyOutputSchema.ReleaseVerifyOutput;

// Source: repl.patch.json
export namespace ReplPatchSchema {
  /**
   * Patch input can be either a JSON Patch array (RFC 6902 subset), a single node patch object, or an array of node patch objects.
   */
  export type ReplPatch = JsonPatchArray | NodePatch | [NodePatch, ...NodePatch[]];
  /**
   * Array of JSON Patch operations.
   *
   * @minItems 1
   */
  export type JsonPatchArray = [JsonPatchOp, ...JsonPatchOp[]];

  /**
   * JSON Patch operation (subset of RFC 6902). Must be used inside an array.
   */
  export interface JsonPatchOp {
    op: 'add' | 'remove' | 'replace';
    path: string;
    value?: any;
  }
  /**
   * Node patch referencing a nodeId plus a relative path within that node.
   */
  export interface NodePatch {
    nodeId: string;
    path: string;
    value?: any;
    op?: 'add' | 'remove' | 'replace';
  }
}
export type ReplPatch = ReplPatchSchema.ReplPatch;

// Source: repl.render.input.json
export namespace ReplRenderInputSchema {
  export type ReplRenderInput = ReplRenderInput1 & ReplRenderInput2;
  export type ReplRenderInput1 = {
    [k: string]: any;
  };
  /**
   * Patch input can be either a JSON Patch array (RFC 6902 subset), a single node patch object, or an array of node patch objects.
   */
  export type AgenticREPLPatch = JsonPatchArray | NodePatch | [NodePatch, ...NodePatch[]];
  /**
   * Array of JSON Patch operations.
   *
   * @minItems 1
   */
  export type JsonPatchArray = [JsonPatchOp, ...JsonPatchOp[]];

  export interface ReplRenderInput2 {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0).
     */
    dslVersion?: string;
    mode?: 'full' | 'patch';
    schema?: AgenticREPLUISchema;
    /**
     * Reference to a cached UiSchema returned by design.compose.
     */
    schemaRef?: string;
    patch?: AgenticREPLPatch;
    baseTree?: AgenticREPLUISchema;
    /**
     * Optional research bundle from Stage1 discovery to influence rendering.
     */
    researchContext?: {
      [k: string]: any;
    };
    options?: {
      includeTree?: boolean;
    };
    /**
     * Optional render output controls. Omitting this object preserves full-document behavior.
     */
    output?: {
      format?: 'document' | 'fragments';
      strict?: boolean;
      includeCss?: boolean;
      /**
       * When true, omit the full token CSS from the response and return a tokenCssRef instead. Reduces response size by ~40%. Default false for repl.render, true for pipeline.
       */
      compact?: boolean;
      /**
       * Reserved for v2 fragment-depth controls; currently ignored.
       */
      depth?: number;
      /**
       * When true, emit data-oods-confidence and data-confidence-level attributes on rendered components that carry composition confidence metadata. Low-confidence components (below confidenceThreshold) also receive an oods-low-confidence CSS class. Default false.
       */
      showConfidence?: boolean;
      /**
       * Confidence threshold for low-confidence affordance. Components with confidence below this value receive the oods-low-confidence CSS class. Only effective when showConfidence is true. Default 0.5.
       */
      confidenceThreshold?: number;
    };
    apply?: boolean;
  }
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
  /**
   * JSON Patch operation (subset of RFC 6902). Must be used inside an array.
   */
  export interface JsonPatchOp {
    op: 'add' | 'remove' | 'replace';
    path: string;
    value?: any;
  }
  /**
   * Node patch referencing a nodeId plus a relative path within that node.
   */
  export interface NodePatch {
    nodeId: string;
    path: string;
    value?: any;
    op?: 'add' | 'remove' | 'replace';
  }
}
export type ReplRenderInput = ReplRenderInputSchema.ReplRenderInput;

// Source: repl.render.output.json
export namespace ReplRenderOutputSchema {
  /**
   * Patch input can be either a JSON Patch array (RFC 6902 subset), a single node patch object, or an array of node patch objects.
   */
  export type AgenticREPLPatch = JsonPatchArray | NodePatch | [NodePatch, ...NodePatch[]];
  /**
   * Array of JSON Patch operations.
   *
   * @minItems 1
   */
  export type JsonPatchArray = [JsonPatchOp, ...JsonPatchOp[]];

  export interface ReplRenderOutput {
    status: 'ok' | 'error';
    mode: 'full' | 'patch';
    dslVersion: string;
    registryVersion?: string | null;
    errors: Issue[];
    warnings: Issue[];
    renderedTree?: AgenticREPLUISchema;
    normalizedPatch?: AgenticREPLPatch;
    appliedPatch?: boolean;
    preview?: {
      screens?: string[];
      routes?: string[];
      activeScreen?: string | null;
      summary?: string;
      notes?: string[];
      /**
       * Passed-through research context for the preview renderer
       */
      researchContext?: {
        [k: string]: any;
      };
    };
    /**
     * Standalone HTML5 document generated when apply=true, output.format=document (or omitted), and render validation passes.
     */
    html?: string;
    /**
     * Reference to the token CSS artifact when compact mode is enabled. Use tokens.build to obtain the full CSS.
     */
    tokenCssRef?: string;
    /**
     * Fragment payload keyed by canonical node id when output.format=fragments.
     */
    fragments?: {
      [k: string]: {
        nodeId: string;
        component: string;
        html: string;
        cssRefs: string[];
      };
    };
    /**
     * Resolved CSS map keyed by cssRef identifier.
     */
    css?: {
      [k: string]: string;
    };
    /**
     * Echoes normalized output controls used by the renderer.
     */
    output?: {
      format: 'document' | 'fragments';
      strict: boolean;
      compact?: boolean;
    };
    meta?: {
      screenCount?: number;
      nodeCount?: number;
      duplicateIds?: string[];
      missingComponents?: string[];
    };
  }
  export interface Issue {
    code: string;
    message: string;
    path?: string;
    hint?: string;
    severity?: 'error' | 'warning';
    component?: string;
    nodeId?: string;
  }
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
  /**
   * JSON Patch operation (subset of RFC 6902). Must be used inside an array.
   */
  export interface JsonPatchOp {
    op: 'add' | 'remove' | 'replace';
    path: string;
    value?: any;
  }
  /**
   * Node patch referencing a nodeId plus a relative path within that node.
   */
  export interface NodePatch {
    nodeId: string;
    path: string;
    value?: any;
    op?: 'add' | 'remove' | 'replace';
  }
}
export type ReplRenderOutput = ReplRenderOutputSchema.ReplRenderOutput;

// Source: repl.ui.schema.json
export namespace UiSchemaSchema {
  export interface UiSchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
}
export type UiSchema = UiSchemaSchema.UiSchema;

// Source: repl.validate.input.json
export namespace ReplValidateInputSchema {
  export type ReplValidateInput = ReplValidateInput1 & ReplValidateInput2;
  export type ReplValidateInput1 = {
    [k: string]: any;
  };
  /**
   * Required when mode='patch'. Accepts JSON Patch array or node patch object(s).
   */
  export type AgenticREPLPatch = JsonPatchArray | NodePatch | [NodePatch, ...NodePatch[]];
  /**
   * Array of JSON Patch operations.
   *
   * @minItems 1
   */
  export type JsonPatchArray = [JsonPatchOp, ...JsonPatchOp[]];

  export interface ReplValidateInput2 {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0).
     */
    dslVersion?: string;
    mode?: 'full' | 'patch';
    schema?: AgenticREPLUISchema;
    /**
     * Reference to a cached UiSchema returned by design.compose.
     */
    schemaRef?: string;
    patch?: AgenticREPLPatch;
    baseTree?: AgenticREPLUISchema1;
    options?: {
      includeNormalized?: boolean;
      checkComponents?: boolean;
      /**
       * When true, run WCAG contrast checks against design tokens and surface failures as A11Y_CONTRAST warnings.
       */
      checkA11y?: boolean;
    };
  }
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
  /**
   * JSON Patch operation (subset of RFC 6902). Must be used inside an array.
   */
  export interface JsonPatchOp {
    op: 'add' | 'remove' | 'replace';
    path: string;
    value?: any;
  }
  /**
   * Node patch referencing a nodeId plus a relative path within that node.
   */
  export interface NodePatch {
    nodeId: string;
    path: string;
    value?: any;
    op?: 'add' | 'remove' | 'replace';
  }
  /**
   * Required when mode='patch' to provide the base UiSchema to patch.
   */
  export interface AgenticREPLUISchema1 {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
}
export type ReplValidateInput = ReplValidateInputSchema.ReplValidateInput;

// Source: repl.validate.output.json
export namespace ReplValidateOutputSchema {
  /**
   * Patch input can be either a JSON Patch array (RFC 6902 subset), a single node patch object, or an array of node patch objects.
   */
  export type AgenticREPLPatch = JsonPatchArray | NodePatch | [NodePatch, ...NodePatch[]];
  /**
   * Array of JSON Patch operations.
   *
   * @minItems 1
   */
  export type JsonPatchArray = [JsonPatchOp, ...JsonPatchOp[]];

  export interface ReplValidateOutput {
    status: 'ok' | 'invalid';
    mode: 'full' | 'patch';
    dslVersion: string;
    registryVersion?: string | null;
    errors: Issue[];
    warnings: Issue[];
    normalizedTree?: AgenticREPLUISchema;
    normalizedPatch?: AgenticREPLPatch;
    appliedPatch?: boolean;
    meta?: {
      screenCount?: number;
      nodeCount?: number;
      duplicateIds?: string[];
      missingComponents?: string[];
    };
  }
  export interface Issue {
    code: string;
    message: string;
    path?: string;
    hint?: string;
    severity?: 'error' | 'warning';
    component?: string;
    nodeId?: string;
  }
  export interface AgenticREPLUISchema {
    $schema?: string;
    version: string;
    dsVersion?: string;
    theme?: string;
    /**
     * @minItems 1
     */
    screens: [UiElement, ...UiElement[]];
    /**
     * Object-level semantic token overrides. Keys are token paths (e.g., 'billing.subscription.status.active'), values are CSS variable references (e.g., 'var(--semantic-success)').
     */
    tokenOverrides?: {
      [k: string]: string;
    };
    /**
     * Object field schema for codegen. Maps field names to type metadata from composed object traits.
     */
    objectSchema?: {
      [k: string]: FieldSchemaEntry;
    };
  }
  export interface UiElement {
    id: string;
    component: string;
    route?: string;
    layout?: Layout;
    style?: Style;
    props?: Props;
    bindings?: Bindings;
    children?: UiElement[];
    meta?: Meta;
  }
  export interface Layout {
    type?: 'stack' | 'grid' | 'inline' | 'section' | 'sidebar';
    align?: 'start' | 'center' | 'end' | 'space-between';
    gapToken?: string;
  }
  export interface Style {
    spacingToken?: string;
    radiusToken?: string;
    shadowToken?: string;
    colorToken?: string;
    typographyToken?: string;
    [k: string]: any;
  }
  export interface Props {
    [k: string]: any;
  }
  export interface Bindings {
    [k: string]: string;
  }
  export interface Meta {
    label?: string;
    intent?: string;
    notes?: string;
    confidence?: number;
    confidenceLevel?: 'high' | 'medium' | 'low';
    /**
     * Raw Stage1 `entity-<slug>` id retained on a composed node when the OODS entity resolver could not map it to an indexed object (Path B, Sprint 89). Consumers surface this so authors can fill the alias table incrementally.
     */
    unresolvedEntity?: string;
  }
  export interface FieldSchemaEntry {
    /**
     * Field data type (string, integer, number, boolean, datetime, email, etc.).
     */
    type: string;
    /**
     * Whether the field is required.
     */
    required: boolean;
    /**
     * Human-readable field description.
     */
    description?: string;
    /**
     * Allowed values for enum-constrained fields.
     */
    enum?: string[];
    /**
     * Semantic type from the object's semantic mapping (e.g., 'billing.subscription.status').
     */
    semanticType?: string;
  }
  /**
   * JSON Patch operation (subset of RFC 6902). Must be used inside an array.
   */
  export interface JsonPatchOp {
    op: 'add' | 'remove' | 'replace';
    path: string;
    value?: any;
  }
  /**
   * Node patch referencing a nodeId plus a relative path within that node.
   */
  export interface NodePatch {
    nodeId: string;
    path: string;
    value?: any;
    op?: 'add' | 'remove' | 'replace';
  }
}
export type ReplValidateOutput = ReplValidateOutputSchema.ReplValidateOutput;

// Source: schema.delete.input.json
export namespace SchemaDeleteInputSchema {
  export interface SchemaDeleteInput {
    name: string;
  }
}
export type SchemaDeleteInput = SchemaDeleteInputSchema.SchemaDeleteInput;

// Source: schema.delete.output.json
export namespace SchemaDeleteOutputSchema {
  export interface SchemaDeleteOutput {
    deleted: true;
    schema: {
      name: string;
      schemaRef: string;
      version: number;
      object?: string;
      context?: string;
      author?: string;
      createdAt: string;
      updatedAt: string;
      tags: string[];
    };
  }
}
export type SchemaDeleteOutput = SchemaDeleteOutputSchema.SchemaDeleteOutput;

// Source: schema.list.input.json
export namespace SchemaListInputSchema {
  export interface SchemaListInput {
    object?: string;
    context?: string;
    tags?: string[];
  }
}
export type SchemaListInput = SchemaListInputSchema.SchemaListInput;

// Source: schema.list.output.json
export namespace SchemaListOutputSchema {
  export type SchemaListOutput = {
    name: string;
    schemaRef: string;
    version: number;
    object?: string;
    context?: string;
    author?: string;
    createdAt: string;
    updatedAt: string;
    tags: string[];
  }[];
}
export type SchemaListOutput = SchemaListOutputSchema.SchemaListOutput;

// Source: schema.load.input.json
export namespace SchemaLoadInputSchema {
  export interface SchemaLoadInput {
    /**
     * Saved schema name in slug format.
     */
    name: string;
  }
}
export type SchemaLoadInput = SchemaLoadInputSchema.SchemaLoadInput;

// Source: schema.load.output.json
export namespace SchemaLoadOutputSchema {
  export interface SchemaLoadOutput {
    schemaRef: string;
    name: string;
    version: number;
    object?: string;
    context?: string;
    author?: string;
    createdAt: string;
    updatedAt: string;
    tags: string[];
  }
}
export type SchemaLoadOutput = SchemaLoadOutputSchema.SchemaLoadOutput;

// Source: schema.save.input.json
export namespace SchemaSaveInputSchema {
  export interface SchemaSaveInput {
    /**
     * Saved schema name in slug format (letters, numbers, hyphens, underscores).
     */
    name: string;
    /**
     * Reference to an in-memory schema produced by design.compose.
     */
    schemaRef: string;
    /**
     * Optional tags for filtering and discovery.
     */
    tags?: string[];
    /**
     * Optional author metadata.
     */
    author?: string;
  }
}
export type SchemaSaveInput = SchemaSaveInputSchema.SchemaSaveInput;

// Source: schema.save.output.json
export namespace SchemaSaveOutputSchema {
  export interface SchemaSaveOutput {
    name: string;
    version: number;
    object?: string;
    context?: string;
    author?: string;
    createdAt: string;
    updatedAt: string;
    tags: string[];
  }
}
export type SchemaSaveOutput = SchemaSaveOutputSchema.SchemaSaveOutput;

// Source: structuredData.fetch.input.json
export namespace StructuredDataFetchInputSchema {
  export interface StructuredDataFetchInput {
    /**
     * Structured dataset to return.
     */
    dataset: 'components' | 'tokens' | 'manifest';
    /**
     * Return matched=true without payload when the ETag matches.
     */
    ifNoneMatch?: string;
    /**
     * When false, omit payload even if no ETag match occurs.
     */
    includePayload?: boolean;
    /**
     * Request a specific date-stamped version (e.g., '2026-02-24'). Omit for latest.
     */
    version?: string;
    /**
     * When true, return available version dates instead of payload.
     */
    listVersions?: boolean;
  }
}
export type StructuredDataFetchInput = StructuredDataFetchInputSchema.StructuredDataFetchInput;

// Source: structuredData.fetch.output.json
export namespace StructuredDataFetchOutputSchema {
  export interface StructuredDataFetchOutput {
    /**
     * Dataset that was requested.
     */
    dataset: 'components' | 'tokens' | 'manifest';
    /**
     * Version tag (usually the YYYY-MM-DD stamp from the manifest).
     */
    version?: string | null;
    /**
     * Timestamp recorded in the payload.
     */
    generatedAt?: string | null;
    /**
     * Stable hash of the payload (generatedAt excluded).
     */
    etag: string;
    /**
     * True when ifNoneMatch matched the current ETag and payload was skipped.
     */
    matched: boolean;
    /**
     * True when the payload field is returned.
     */
    payloadIncluded: boolean;
    /**
     * Resolved path to the dataset on disk.
     */
    path: string;
    /**
     * Manifest path when available.
     */
    manifestPath?: string | null;
    /**
     * File size of the dataset.
     */
    sizeBytes: number;
    /**
     * True when the payload was validated against a schema.
     */
    schemaValidated: boolean;
    /**
     * Optional validation error messages.
     */
    validationErrors?: string[];
    /**
     * Non-fatal warnings encountered during resolution.
     */
    warnings?: string[];
    /**
     * Lightweight summary for the payload.
     */
    meta?: {
      componentCount?: number;
      traitCount?: number;
      objectCount?: number;
      domainCount?: number;
      patternCount?: number;
      traitOverlayCount?: number;
      tokenCounts?: {
        referenceTokens?: number;
        themeTokens?: number;
        systemTokens?: number;
        componentTokens?: number;
        viewTokens?: number;
        mapCount?: number;
        traitOverlayCount?: number;
      };
      [k: string]: any;
    };
    /**
     * Payload contents when payloadIncluded=true.
     */
    payload?: {
      [k: string]: any;
    };
    /**
     * Available version dates when listVersions=true.
     */
    availableVersions?: string[];
    /**
     * The version that was requested (null if latest).
     */
    requestedVersion?: string | null;
    /**
     * The version that was actually resolved (may differ from requested if nearest match used).
     */
    resolvedVersion?: string | null;
  }
}
export type StructuredDataFetchOutput = StructuredDataFetchOutputSchema.StructuredDataFetchOutput;

// Source: tokens.build.input.json
export namespace TokensBuildInputSchema {
  export interface TokensBuildInput {
    brand?: 'A';
    theme?: 'light' | 'dark' | 'hc';
    apply?: boolean;
  }
}
export type TokensBuildInput = TokensBuildInputSchema.TokensBuildInput;

// Source: viz.compose.input.json
export namespace VizComposeInputSchema {
  /**
   * Compose a visualization schema from chart type, data bindings, and/or object viz traits. Provide at least one of 'chartType', 'object', or 'traits'.
   */
  export type VizComposeInput = VizComposeInput1 & VizComposeInput2;
  export type VizComposeInput1 = {
    [k: string]: any;
  };

  export interface VizComposeInput2 {
    /**
     * DSL version to use for this request. Defaults to the current version (1.0).
     */
    dslVersion?: string;
    /**
     * Object name from the OODS registry. When provided, viz traits are resolved automatically to determine chart type and encodings.
     */
    object?: string;
    /**
     * Explicit viz trait names (e.g., 'mark-bar', 'encoding-position-x'). Used when composing without an object.
     *
     * @minItems 1
     */
    traits?: [string, ...string[]];
    /**
     * Chart type to compose. Maps to mark traits: bar→mark-bar, line→mark-line, area→mark-area, point→mark-point, scatter→mark-scatter, heatmap→mark-heatmap.
     */
    chartType?: 'bar' | 'line' | 'area' | 'point' | 'scatter' | 'heatmap';
    dataBindings?: {
      /**
       * Field name for the x-axis encoding.
       */
      x?: string;
      /**
       * Field name for the y-axis encoding.
       */
      y?: string;
      /**
       * Field name for color encoding.
       */
      color?: string;
      /**
       * Field name for size encoding.
       */
      size?: string;
      /**
       * Field name for opacity encoding.
       */
      opacity?: string;
      /**
       * Field name for shape encoding.
       */
      shape?: string;
    };
    /**
     * Alias for dataBindings. Maps field names to encoding channels.
     */
    data?: {
      /**
       * Field name for the x-axis encoding.
       */
      x?: string;
      /**
       * Field name for the y-axis encoding.
       */
      y?: string;
      /**
       * Field name for color encoding.
       */
      color?: string;
      /**
       * Field name for size encoding.
       */
      size?: string;
      /**
       * Field name for opacity encoding.
       */
      opacity?: string;
      /**
       * Field name for shape encoding.
       */
      shape?: string;
    };
    /**
     * Theme token (e.g., 'light', 'dark').
     */
    theme?: string;
    options?: {
      /**
       * Auto-validate the generated schema.
       */
      validate?: boolean;
    };
  }
}
export type VizComposeInput = VizComposeInputSchema.VizComposeInput;

// Source: viz.compose.output.json
export namespace VizComposeOutputSchema {
  /**
   * Visualization schema with component tree, slots, props, and token mappings.
   */
  export interface VizComposeOutput {
    /**
     * Whether the composition succeeded.
     */
    status: 'ok' | 'error';
    /**
     * Resolved chart type (bar, line, area, point, scatter, heatmap, or empty on error).
     */
    chartType: string;
    /**
     * The composed UiSchema tree with viz components.
     */
    schema: {
      [k: string]: any;
    };
    /**
     * Temporary schema reference for pipeline reuse in validate/render/codegen.
     */
    schemaRef?: string;
    /**
     * ISO timestamp when the schemaRef was created.
     */
    schemaRefCreatedAt?: string;
    /**
     * ISO timestamp when the schemaRef expires.
     */
    schemaRefExpiresAt?: string;
    /**
     * Slot assignments mapping viz components to chart regions.
     */
    slots: SlotEntry[];
    /**
     * Non-fatal issues encountered during composition.
     */
    warnings: Issue[];
    /**
     * Fatal errors (present when status is 'error').
     */
    errors?: Issue[];
    meta?: {
      /**
       * Viz traits that were resolved during composition.
       */
      traitsResolved?: string[];
      /**
       * Encoding traits applied to axis/scale config.
       */
      encodingsApplied?: string[];
      /**
       * Number of viz components placed in the schema.
       */
      componentCount?: number;
      /**
       * Object name if object-based composition was used.
       */
      objectUsed?: string;
      /**
       * Layout composition strategy: single, layer, facet, or concat.
       */
      layoutStrategy?: string;
      /**
       * Scale traits resolved (e.g., scale-linear, scale-temporal).
       */
      scalesResolved?: string[];
      /**
       * Interaction traits resolved (e.g., interaction-tooltip, interaction-highlight).
       */
      interactionsResolved?: string[];
    };
  }
  export interface SlotEntry {
    slotName: string;
    component: string;
    props: {
      [k: string]: any;
    };
  }
  export interface Issue {
    code: string;
    message: string;
    path?: string;
    hint?: string;
  }
}
export type VizComposeOutput = VizComposeOutputSchema.VizComposeOutput;

// Canonical aliases for shared REPL/UI schema shapes.
export type UiElement = UiSchemaSchema.UiElement;
export type UiLayout = UiSchemaSchema.Layout;
export type UiStyle = UiSchemaSchema.Style;
export type UiProps = UiSchemaSchema.Props;
export type UiBindings = UiSchemaSchema.Bindings;
export type UiMeta = UiSchemaSchema.Meta;
export type FieldSchemaEntry = UiSchemaSchema.FieldSchemaEntry;

export type ReplJsonPatchOperation = ReplPatchSchema.JsonPatchOp;
export type ReplNodePatch = ReplPatchSchema.NodePatch;

export type ReplIssue = ReplRenderOutputSchema.Issue;
export type ReplRenderPreview = NonNullable<ReplRenderOutput['preview']>;
export type ReplValidationMeta = NonNullable<ReplRenderOutput['meta']>;
export type ReplRenderFormat = NonNullable<NonNullable<ReplRenderOutput['output']>['format']>;
