import type { ContrastRule } from './types.js';

export const DEFAULT_CONTRAST_RULES: ReadonlyArray<ContrastRule> = [
  {
    ruleId: 'text-on-surface',
    target: 'sys.text.primary on sys.surface.canvas',
    foreground: 'sys.text.primary',
    background: 'sys.surface.canvas',
    threshold: 4.5,
    summary: 'Primary text on the default surface must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'text-on-surface-dark',
    target: 'theme-dark.text.primary on theme-dark.surface.canvas',
    foreground: 'theme-dark.text.primary',
    background: 'theme-dark.surface.canvas',
    threshold: 4.5,
    summary: 'Dark theme primary text on canvas must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'text-on-surface-dark-raised',
    target: 'theme-dark.text.primary on theme-dark.surface.raised',
    foreground: 'theme-dark.text.primary',
    background: 'theme-dark.surface.raised',
    threshold: 4.5,
    summary: 'Dark theme primary text on raised surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'text-on-surface-dark-subtle',
    target: 'theme-dark.text.primary on theme-dark.surface.subtle',
    foreground: 'theme-dark.text.primary',
    background: 'theme-dark.surface.subtle',
    threshold: 4.5,
    summary: 'Dark theme primary text on subtle surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'inverse-text',
    target: 'sys.text.inverse on sys.surface.inverse',
    foreground: 'sys.text.inverse',
    background: 'sys.surface.inverse',
    threshold: 4.5,
    summary: 'Inverse text must meet 4.5:1 contrast on inverse surfaces.',
  },
  {
    ruleId: 'text-on-raised',
    target: 'sys.text.primary on sys.surface.raised',
    foreground: 'sys.text.primary',
    background: 'sys.surface.raised',
    threshold: 4.5,
    summary: 'Primary text on raised surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'text-on-subtle',
    target: 'sys.text.primary on sys.surface.subtle',
    foreground: 'sys.text.primary',
    background: 'sys.surface.subtle',
    threshold: 4.5,
    summary: 'Primary text on subtle surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'secondary-text',
    target: 'sys.text.secondary on sys.surface.canvas',
    foreground: 'sys.text.secondary',
    background: 'sys.surface.canvas',
    threshold: 4.5,
    summary: 'Secondary headings on default surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'muted-text',
    target: 'sys.text.muted on sys.surface.canvas',
    foreground: 'sys.text.muted',
    background: 'sys.surface.canvas',
    threshold: 4.5,
    summary: 'Muted body text on default surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'accent-text',
    target: 'sys.text.accent on sys.surface.canvas',
    foreground: 'sys.text.accent',
    background: 'sys.surface.canvas',
    threshold: 4.5,
    summary: 'Inline links on default surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'status-info-text',
    target: 'sys.status.info.text on sys.status.info.surface',
    foreground: 'sys.status.info.text',
    background: 'sys.status.info.surface',
    threshold: 4.5,
    summary: 'Info text inside info surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'status-success-text',
    target: 'sys.status.success.text on sys.status.success.surface',
    foreground: 'sys.status.success.text',
    background: 'sys.status.success.surface',
    threshold: 4.5,
    summary: 'Success text inside success surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'status-warning-text',
    target: 'sys.status.warning.text on sys.status.warning.surface',
    foreground: 'sys.status.warning.text',
    background: 'sys.status.warning.surface',
    threshold: 4.5,
    summary: 'Warning text inside warning surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'status-critical-text',
    target: 'sys.status.critical.text on sys.status.critical.surface',
    foreground: 'sys.status.critical.text',
    background: 'sys.status.critical.surface',
    threshold: 4.5,
    summary: 'Critical text inside critical surfaces must meet 4.5:1 contrast.',
  },
  {
    ruleId: 'status-info-icon',
    target: 'sys.status.info.icon on sys.status.info.surface',
    foreground: 'sys.status.info.icon',
    background: 'sys.status.info.surface',
    threshold: 3,
    summary: 'Info icons inside info surfaces must meet 3:1 contrast.',
  },
  {
    ruleId: 'status-success-icon',
    target: 'sys.status.success.icon on sys.status.success.surface',
    foreground: 'sys.status.success.icon',
    background: 'sys.status.success.surface',
    threshold: 3,
    summary: 'Success icons inside success surfaces must meet 3:1 contrast.',
  },
  {
    ruleId: 'status-warning-icon',
    target: 'sys.status.warning.icon on sys.status.warning.surface',
    foreground: 'sys.status.warning.icon',
    background: 'sys.status.warning.surface',
    threshold: 3,
    summary: 'Warning icons inside warning surfaces must meet 3:1 contrast.',
  },
  {
    ruleId: 'status-critical-icon',
    target: 'sys.status.critical.icon on sys.status.critical.surface',
    foreground: 'sys.status.critical.icon',
    background: 'sys.status.critical.surface',
    threshold: 3,
    summary: 'Critical icons inside critical surfaces must meet 3:1 contrast.',
  },
];
