import { z } from 'zod';

import { TAG_STATES } from './constants.js';
import {
  CATEGORY_IDENTIFIER_PATTERN,
  CATEGORY_SLUG_PATTERN,
  normalizeIdentifier,
  normalizeSlug,
  normalizeSynonymList,
} from './utils.js';

export const TagSchema = z
  .object({
    id: z
      .string()
      .regex(CATEGORY_IDENTIFIER_PATTERN, 'tag identifiers must use lowercase letters, numbers, "_" or "-".'),
    name: z
      .string()
      .trim()
      .min(1)
      .max(80),
    slug: z
      .string()
      .regex(CATEGORY_SLUG_PATTERN, 'tag slugs must be kebab-case.'),
    usageCount: z
      .number()
      .int()
      .min(0)
      .max(10_000_000),
    state: z.enum(TAG_STATES),
    synonyms: z.array(
      z
        .string()
        .trim()
        .min(1)
        .max(80)
    ),
    isCanonical: z.boolean(),
    createdAt: z.string().datetime().optional(),
    updatedAt: z.string().datetime().optional(),
    metadata: z
      .object({
        lastAppliedAt: z.string().datetime().optional(),
        autoGenerated: z.boolean().optional(),
        flaggedReason: z
          .string()
          .trim()
          .min(4)
          .max(280)
          .optional(),
        synonymOf: z
          .string()
          .min(2)
          .max(64)
          .optional(),
      })
      .strip()
      .optional(),
  })
  .strict()
  .transform((value) => ({
    ...value,
    synonyms: Object.freeze([...value.synonyms]),
    metadata: value.metadata ? Object.freeze({ ...value.metadata }) : undefined,
  }));

export type Tag = z.infer<typeof TagSchema>;
export type TagInput = Omit<z.input<typeof TagSchema>, 'synonyms'> & {
  readonly synonyms?: readonly string[];
};

/**
 * Normalize a Tag object using slug + identifier rules and deduplicated synonym lists.
 */
export function normalizeTag(input: TagInput): Tag {
  if (!input) {
    throw new TypeError('Tag input is required.');
  }

  const name = typeof input.name === 'string' ? input.name.trim() : '';
  if (!name) {
    throw new Error('Tag name is required.');
  }

  const id = normalizeIdentifier(typeof input.id === 'string' ? input.id : name);
  const slug = normalizeSlug(typeof input.slug === 'string' ? input.slug : name);

  return TagSchema.parse({
    ...input,
    id,
    slug,
    name,
    synonyms: normalizeSynonymList(input.synonyms, 16),
    usageCount: input.usageCount ?? 0,
    state: input.state ?? 'active',
    isCanonical: input.isCanonical ?? true,
  });
}
